// Exercise pictures — the manifest, and how a picture is found for an exercise.
//
// Tim, 2026-08-30: "I want to have a way to display pictures of the exercises so
// the user knows what it looks like in the app, no matter where it is
// displayed… if the user clicks on the name of the exercise, it will pull up
// the picture that takes up the screen."
//
// Pure: no DOM, no store.
//
// ⚠️ THERE ARE NO PICTURES IN THIS REPOSITORY YET, AND THAT IS THE POINT OF
// THIS FILE. The art style Tim wants is Gym Visual's, which is a paid stock
// library — the biggest public dataset that re-hosts it says in its own licence
// "obtain your own license there before reusing the media". So the FEATURE is
// built and the ART is a purchase Tim makes when he wants to. Everything
// downstream of here treats "no picture" as an ordinary state rather than as a
// missing file: no placeholder, no broken-image box, no empty square. A screen
// with no picture looks exactly like it did before this shipped.
//
// ⚠️ This is the second time this project has met a licensing wall on somebody
// else's anatomy art — `docs/research.md` §11 records the watermarked Dreamstime
// asset that could not be used, which is why the body map is hand-authored.
//
// ── HOW TO ADD PICTURES ──────────────────────────────────────────────────────
//
//   1. Drop files into `img/exercises/`, named for the exercise's ID:
//        img/exercises/barbell-bench-press--chest.webp
//      The id is `slugify(name) + '--' + slugify(muscle)` — see exercises.js.
//      ⚠️ The muscle half is not decoration: `Cable Kickback` exists TWICE in
//      the library, once for Triceps and once for Glutes, and the id is the
//      only thing that tells them apart.
//   2. Run `node tools/build-exercise-images.mjs`.
//      It rewrites the MANIFEST below and the precache list in `sw.js`.
//   3. Commit both.
//
// ⚠️ WHY A MANIFEST RATHER THAN "JUST TRY TO LOAD IT". Two reasons, and the
// first is not negotiable. **D6: the app must work with no network**, and
// `sw.js` can only precache a file it is told about — an image discovered by
// trying to fetch it is an image that is missing in a gym basement. Second, a
// speculative <img> per row is a 404 per row on every screen that lists
// exercises, which is a slow way to find out nothing is there.
//
// ⚠️ AND THE MANIFEST IS GENERATED, NEVER HAND-EDITED. A hand-kept list of 275
// filenames is a list that drifts from the directory, and the drift is silent:
// a name typed wrong shows no picture, which is exactly what "no picture yet"
// looks like. `tests/data-layer.test.mjs` asserts the manifest matches what is
// actually on disk, so a forgotten rebuild fails loudly.

/**
 * Exercise id → file extension. GENERATED by tools/build-exercise-images.mjs.
 * Empty until Tim buys the art; every consumer already handles that.
 */
export const MANIFEST = {
  // BEGIN GENERATED
  // END GENERATED
};

/** Where the files live, relative to index.html. */
export const IMAGE_DIR = 'img/exercises/';

/**
 * The picture for an exercise, or null if there isn't one.
 *
 * ⚠️ Takes the exercise OBJECT, not a name. Two exercises in this library share
 * the name "Cable Kickback" and only the id separates them, so a name-keyed
 * lookup would eventually show a triceps picture over a glute exercise.
 */
export function imageFor(exercise) {
  if (!exercise || !exercise.id) return null;
  const ext = MANIFEST[exercise.id];
  return ext ? `${IMAGE_DIR}${exercise.id}.${ext}` : null;
}

/** Same, for a bare id — used where a session row carries the id and no object. */
export function imageForId(id) {
  const ext = id ? MANIFEST[id] : null;
  return ext ? `${IMAGE_DIR}${id}.${ext}` : null;
}

/** Is there any art at all? Screens use this to stay silent about the feature. */
export function hasImages() {
  return Object.keys(MANIFEST).length > 0;
}

/** Every file the manifest claims, for the service worker and the tests. */
export function manifestPaths() {
  return Object.entries(MANIFEST).map(([id, ext]) => `${IMAGE_DIR}${id}.${ext}`);
}
