/* GENERATED BY tools/build-rep-sigma.mjs — DO NOT HAND-EDIT.
 *
 * How uncertain the rep→1RM conversion is, per rep count, measured as the
 * disagreement between the seven classical formulas in docs/research.md §1.2
 * after normalising each by its own one-rep value.
 *
 * 🚨 THIS REPLACED A HAND-TYPED LADDER. `repFactor()` used to assert
 * 1.00 / 0.95 / 0.85 / 0.70 / 0.45 / 0.25 with no source for any of it, and one
 * extra rep could cost a set a third of its weight at the step boundaries. Tim
 * asked where 0.45 came from; nothing anywhere answered.
 *
 * ⚠️ A ONE-REP SET HAS σ = 0 because nothing is converted. The rise is smooth
 * and monotone, which the ladder was not.
 *
 * Regenerate: node tools/build-rep-sigma.mjs --write
 */

/** Relative σ of the rep→1RM conversion, indexed by rep count (1-based). */
export const REP_SIGMA = new Map([
  [1, 0.00000],
  [2, 0.01627],
  [3, 0.02226],
  [4, 0.02449],
  [5, 0.02530],
  [6, 0.02604],
  [7, 0.02767],
  [8, 0.03078],
  [9, 0.03558],
  [10, 0.04204],
  [11, 0.05002],
  [12, 0.05942],
  [13, 0.07016],
  [14, 0.08226],
  [15, 0.09575],
]);

/**
 * The conversion uncertainty for a set of `reps` reps, as a fraction.
 *
 * ⚠️ Above D5's ceiling the set is not evidence of a maximum and the caller
 * should already have refused it; this returns the ceiling's σ rather than
 * extrapolating a table that stops.
 */
export function repSigma(reps) {
  const r = Math.round(Number(reps));
  if (!Number.isFinite(r) || r < 1) return REP_SIGMA.get(15);
  return REP_SIGMA.get(Math.min(r, 15));
}
