"""Build README.md for a channel's notes folder.

Usage:
    python tools/build_channel_readme.py <sourcedir> <notesdir> <intro.md>

The Menno version of this (tools/build_menno_readme.py) had to guess a note's
section from keywords in its title, because those notes predated the convention.
This one does not guess: every note carries a `**Topic:**` line drawn from a
fixed vocabulary, so the partition is read straight off the notes themselves and
a note that is missing or malformed is reported rather than quietly filed
somewhere plausible.

<intro.md> is the hand-written prose that goes above the index - what the source
is, why it is in the library, and how to read its citations. That part is
judgement and does not belong in a script; everything below it is mechanical.

Section order is the order topics are listed in TOPIC_ORDER, so the index opens
with the material this library has most of rather than in alphabetical order.
"""
import collections
import io
import os
import re
import sys

# The vocabulary the note brief hands to the agents, in reading order rather
# than alphabetically: what you pick, then how you do it, then how much.
TOPIC_ORDER = [
    "Exercise selection",
    "Range of motion & tempo",
    "Load & reps",
    "Volume & frequency",
    "Effort & failure",
    "Programming",
    "Mechanisms",
    "Nutrition",
    "Evidence & method",
]


def read_rows(src):
    rows = []
    path = os.path.join(src, "assignments.tsv")
    for line in io.open(path, encoding="utf-8-sig"):
        p = line.rstrip("\n").split("\t")
        if len(p) >= 5:
            rows.append({"id": p[0], "file": p[1], "min": int(p[2]),
                         "refs": int(p[3]), "title": p[4]})
    return rows


def header_of(notes, fn):
    """The note's own H1 and Topic. None if the file is not there."""
    path = os.path.join(notes, fn)
    if not os.path.exists(path):
        return None
    head = io.open(path, encoding="utf-8-sig").read(2000)
    h1 = re.search(r"^#\s+(.+)$", head, re.M)
    topic = re.search(r"^\*\*Topic:\*\*\s*(.+)$", head, re.M)
    return {
        "h1": h1.group(1).strip() if h1 else None,
        "topic": topic.group(1).strip().strip("*").split("·")[0].strip()
        if topic else None,
    }


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    src, notes, intro = sys.argv[1], sys.argv[2], sys.argv[3]

    rows = read_rows(src)
    groups = collections.OrderedDict((t, []) for t in TOPIC_ORDER)
    missing, untopiced, unknown = [], [], []

    for r in rows:
        h = header_of(notes, r["file"])
        if h is None:
            missing.append(r["file"])
            continue
        r["h1"] = h["h1"] or r["title"]
        t = h["topic"]
        if not t:
            untopiced.append(r["file"])
            continue
        if t not in groups:
            unknown.append((r["file"], t))
            groups[t] = []
        groups[t].append(r)

    body = [io.open(intro, encoding="utf-8-sig").read().rstrip(), "",
            "---", "", "## Every note"]
    for name, recs in groups.items():
        if not recs:
            continue
        recs.sort(key=lambda r: (-r["min"], r["h1"].lower()))
        body.append("\n### %s (%d)\n" % (name, len(recs)))
        for r in recs:
            ref = " · %d refs" % r["refs"] if r["refs"] else " · no reference list"
            body.append("- [%s](%s)  \n  *%d min%s*" % (r["h1"], r["file"], r["min"], ref))
        body.append("")

    body.append("""
---

Notes written from the videos' caption tracks fetched with `tools/fetch_channel.py`;
references extracted from the descriptions with `tools/extract_refs_desc.py` and resolved
against PubMed, the NCBI ID converter and Crossref with `tools/resolve_refs.py`. This index
is generated by `tools/build_channel_readme.py` from each note's own `**Topic:**` line, so
it cannot drift from the notes.

These are notes, not transcripts, and they do not reproduce his script. If you want his
exact words, watch the video.
""")

    io.open(os.path.join(notes, "README.md"), "w", encoding="utf-8",
            newline="\n").write("\n".join(body))

    filed = sum(len(v) for v in groups.values())
    print("wrote README.md: %d of %d notes across %d sections"
          % (filed, len(rows), sum(1 for v in groups.values() if v)))
    if missing:
        print("NOT WRITTEN (%d): %s" % (len(missing), ", ".join(missing)))
    if untopiced:
        print("NO TOPIC LINE (%d): %s" % (len(untopiced), ", ".join(untopiced)))
    if unknown:
        print("TOPIC OUTSIDE THE VOCABULARY (%d):" % len(unknown))
        for fn, t in unknown:
            print("   %s -> %r" % (fn, t))


main()
