"""Build README.md for a channel's notes folder.

Usage:
    python tools/build_channel_readme.py <sourcedir> <notesdir> <intro.md> [topic-set]

The Menno version of this (tools/build_menno_readme.py) had to guess a note's
section from keywords in its title, because those notes predated the convention.
This one does not guess: every note carries a `**Topic:**` line drawn from a
fixed vocabulary, so the partition is read straight off the notes themselves and
a note that is missing or malformed is reported rather than quietly filed
somewhere plausible.

<intro.md> is the hand-written prose that goes above the index - what the source
is, why it is in the library, and how to read its citations. That part is
judgement and does not belong in a script; everything below it is mechanical.

Section order is the order topics are listed in TOPIC_ORDER, so the index opens
with the material this library has most of rather than in alphabetical order.
"""
import collections
import io
import os
import re
import sys

# The vocabularies the note briefs hand to the agents, in reading order rather
# than alphabetically. Each source gets its own list because the sensible
# ordering differs: a hypertrophy channel opens on exercise selection, a
# clinical source opens on injury. A topic missing from the chosen list is
# reported rather than filed somewhere plausible.
TOPIC_SETS = {
    # Hypertrophy video sources: what you pick, then how you do it, then how much.
    "training": [
        "Exercise selection",
        "Range of motion & tempo",
        "Load & reps",
        "Volume & frequency",
        "Effort & failure",
        "Programming",
        "Mechanisms",
        "Nutrition",
        "Evidence & method",
    ],
    # Barbell Medicine: clinicians first, because that is why the source is here.
    "clinical": [
        "Injury & rehabilitation",
        "Pain science",
        "Health & medicine",
        "Exercise selection & technique",
        "Load & reps",
        "Volume & recovery",
        "Programming",
        "Nutrition",
        "Evidence & method",
    ],
}
TOPIC_ORDER = TOPIC_SETS["training"]

# Column 3 of assignments.tsv is runtime for a video source and word count for a
# written one, so the index has to say which.
FOOTERS = {
    "training": """
---

Notes written from the videos' caption tracks fetched with `tools/fetch_channel.py`;
references extracted from the descriptions with `tools/extract_refs_desc.py` and resolved
against PubMed, the NCBI ID converter and Crossref with `tools/resolve_refs.py`. This index
is generated by `tools/build_channel_readme.py` from each note's own `**Topic:**` line, so
it cannot drift from the notes.

These are notes, not transcripts, and they do not reproduce the creator's script. If you
want the exact words, watch the video.
""",
    "clinical": """
---

Notes written from the articles fetched with `tools/fetch_articles.py`; references extracted
with `tools/extract_refs_article.py`, which records each inline `[n]` marker against the
sentence it was cited on, and resolved against PubMed, the NCBI ID converter and Crossref
with `tools/resolve_refs.py`. This index is generated by `tools/build_channel_readme.py`
from each note's own `**Topic:**` line, so it cannot drift from the notes.

These are notes, not reproductions. Barbell Medicine's terms permit reading and summarising,
not republishing; nothing here reproduces their text. If you want the article, follow the
link at the top of the note.
""",
}


def size(n):
    """Column 3 means minutes for a video source, words for a written one."""
    return "%d min" % n if n < 200 else "{:,} words".format(n)


def read_rows(src):
    rows = []
    path = os.path.join(src, "assignments.tsv")
    for line in io.open(path, encoding="utf-8-sig"):
        p = line.rstrip("\n").split("\t")
        if len(p) >= 5:
            rows.append({"id": p[0], "file": p[1], "min": int(p[2]),
                         "refs": int(p[3]), "title": p[4]})
    return rows


def header_of(notes, fn):
    """The note's own H1 and Topic. None if the file is not there."""
    path = os.path.join(notes, fn)
    if not os.path.exists(path):
        return None
    head = io.open(path, encoding="utf-8-sig").read(2000)
    h1 = re.search(r"^#\s+(.+)$", head, re.M)
    topic = re.search(r"^\*\*Topic:\*\*\s*(.+)$", head, re.M)
    return {
        "h1": h1.group(1).strip() if h1 else None,
        "topic": topic.group(1).strip().strip("*").split("·")[0].strip()
        if topic else None,
    }


def main():
    if len(sys.argv) not in (4, 5):
        sys.exit(__doc__)
    src, notes, intro = sys.argv[1], sys.argv[2], sys.argv[3]
    topics = TOPIC_SETS[sys.argv[4]] if len(sys.argv) > 4 else TOPIC_ORDER

    rows = read_rows(src)
    groups = collections.OrderedDict((x, []) for x in topics)
    missing, untopiced, unknown = [], [], []

    for r in rows:
        h = header_of(notes, r["file"])
        if h is None:
            missing.append(r["file"])
            continue
        r["h1"] = h["h1"] or r["title"]
        t = h["topic"]
        if not t:
            untopiced.append(r["file"])
            continue
        if t not in groups:
            unknown.append((r["file"], t))
            groups[t] = []
        groups[t].append(r)

    body = [io.open(intro, encoding="utf-8-sig").read().rstrip(), "",
            "---", "", "## Every note"]
    for name, recs in groups.items():
        if not recs:
            continue
        recs.sort(key=lambda r: (-r["min"], r["h1"].lower()))
        body.append("\n### %s (%d)\n" % (name, len(recs)))
        for r in recs:
            ref = " · %d refs" % r["refs"] if r["refs"] else " · no reference list"
            body.append("- [%s](%s)  \n  *%s%s*"
                        % (r["h1"], r["file"], size(r["min"]), ref))
        body.append("")

    body.append(FOOTERS["clinical" if topics is TOPIC_SETS["clinical"]
                        else "training"])

    io.open(os.path.join(notes, "README.md"), "w", encoding="utf-8",
            newline="\n").write("\n".join(body))

    filed = sum(len(v) for v in groups.values())
    print("wrote README.md: %d of %d notes across %d sections"
          % (filed, len(rows), sum(1 for v in groups.values() if v)))
    if missing:
        print("NOT WRITTEN (%d): %s" % (len(missing), ", ".join(missing)))
    if untopiced:
        print("NO TOPIC LINE (%d): %s" % (len(untopiced), ", ".join(untopiced)))
    if unknown:
        print("TOPIC OUTSIDE THE VOCABULARY (%d):" % len(unknown))
        for fn, t in unknown:
            print("   %s -> %r" % (fn, t))


main()
